### ISSUE TITLE
精选歌单列表中文字过多的问题

### ISSUE THREAD

**Issue by davinma** [listen1/listen1_chrome_extension#54]
列表图片下文字过多（超过两行），会被下面一行的图片遮住。原因是 `.playlist-covers li` 限定了高度为 188px。<br/>
推荐改为自适应高度：

``` CSS
.playlist-covers li {
    /* float: left; */
    display: inline-block;
    width: 140px;
    /* height: 188px; */
    margin-right: 22px;
    vertical-align: top;
}
```

或者给文字区域限定高度：

``` CSS
.playlist-covers .desc {
    text-align: left;
    height: 40px;
    overflow: hidden;
}
```
